trigger:
  branches:
    include:
      - master
      - refs/tags/*
stages:
  - stage: Build
    jobs:
    - job: BuildDesktopGL
      displayName: Desktop GL
      pool:
        vmImage: xcode9-macos10.13
      steps:
      - bash: |
          ls -la /Library/Frameworks/Mono.framework/Versions
          wget -O MonoGame.pkg https://github.com/MonoGame/MonoGame/releases/download/v3.7.1/MonoGame.pkg
          sudo installer -pkg "MonoGame.pkg" -target /
          SYMLINK=6_0_0
          MONOPREFIX=/Library/Frameworks/Mono.framework/Versions/$SYMLINK
          echo "##vso[task.setvariable variable=DYLD_FALLBACK_LIBRARY_PATH;]$MONOPREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
          echo "##vso[task.setvariable variable=PKG_CONFIG_PATH;]$MONOPREFIX/lib/pkgconfig:$MONOPREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
          echo "##vso[task.setvariable variable=PATH;]$MONOPREFIX/bin:$PATH"
          nuget restore VectorRumble.sln
      - task: MSBuild@1
        displayName: 'Build solution VectorRumble.Desktop/VectorRumble.Desktop.csproj'
        inputs:
          solution: VectorRumble.Desktop/VectorRumble.Desktop.csproj
          configuration: Release
          msbuildArguments: /restore /v:diag
    - job: BuildUWP
      displayName: UWP
      pool:
        vmImage: vs2017-win2016
      steps:
      - bash: |
          curl -o MonoGameSetup.exe -L https://github.com/MonoGame/MonoGame/releases/download/v3.7.1/MonoGameSetup.exe
      - script: |
          dir
          MonoGameSetup.exe /S
      - task: NuGetCommand@2
        inputs:
          command: 'restore'
          restoreSolution: 'VectorRumble.sln'
      - task: MSBuild@1
        displayName: 'Build solution VectorRumble.UWP/VectorRumble.UWP.csproj'
        inputs:
          solution: VectorRumble.UWP/VectorRumble.UWP.csproj
          configuration: Release
          msbuildArguments: /restore /v:diag /p:AppxPackage=false
