//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VectorRumble {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("VectorRumble.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Play_Game {
            get {
                return ResourceManager.GetString("Play Game", resourceCulture);
            }
        }
        
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        internal static string Exit_Prompt {
            get {
                return ResourceManager.GetString("Exit_Prompt", resourceCulture);
            }
        }
        
        internal static string MessageBox_Usage {
            get {
                return ResourceManager.GetString("MessageBox_Usage", resourceCulture);
            }
        }
        
        internal static string Resume_Game {
            get {
                return ResourceManager.GetString("Resume Game", resourceCulture);
            }
        }
        
        internal static string Quit_Game {
            get {
                return ResourceManager.GetString("Quit Game", resourceCulture);
            }
        }
        
        internal static string Are_You_Sure {
            get {
                return ResourceManager.GetString("Are_You_Sure", resourceCulture);
            }
        }
        
        internal static string Play_Again {
            get {
                return ResourceManager.GetString("Play_Again", resourceCulture);
            }
        }
        
        internal static string Return_to_Menu {
            get {
                return ResourceManager.GetString("Return_to_Menu", resourceCulture);
            }
        }
        
        internal static string Player_X_Wins {
            get {
                return ResourceManager.GetString("Player_X_Wins", resourceCulture);
            }
        }
        
        internal static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        internal static string Hold_A_To_Join {
            get {
                return ResourceManager.GetString("Hold_A_To_Join", resourceCulture);
            }
        }
        
        internal static string Press_W_To_Join {
            get {
                return ResourceManager.GetString("Press_W_To_Join", resourceCulture);
            }
        }
        
        internal static string Press_Up_To_Join {
            get {
                return ResourceManager.GetString("Press_Up_To_Join", resourceCulture);
            }
        }
        
        internal static string Connect_Gamepad {
            get {
                return ResourceManager.GetString("Connect_Gamepad", resourceCulture);
            }
        }
        
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        internal static string Score_Limit {
            get {
                return ResourceManager.GetString("Score_Limit", resourceCulture);
            }
        }
        
        internal static string Asteroid_Density {
            get {
                return ResourceManager.GetString("Asteroid_Density", resourceCulture);
            }
        }
        
        internal static string Arena {
            get {
                return ResourceManager.GetString("Arena", resourceCulture);
            }
        }
        
        internal static string Motion_Blur {
            get {
                return ResourceManager.GetString("Motion_Blur", resourceCulture);
            }
        }
        
        internal static string Neon_Effect {
            get {
                return ResourceManager.GetString("Neon_Effect", resourceCulture);
            }
        }
        
        internal static string Blur_Intesity {
            get {
                return ResourceManager.GetString("Blur_Intesity", resourceCulture);
            }
        }
        
        internal static string Asteroid_Density_None {
            get {
                return ResourceManager.GetString("Asteroid_Density_None", resourceCulture);
            }
        }
        
        internal static string Asteroid_Density_Low {
            get {
                return ResourceManager.GetString("Asteroid_Density_Low", resourceCulture);
            }
        }
        
        internal static string Asteroid_Density_Medium {
            get {
                return ResourceManager.GetString("Asteroid_Density_Medium", resourceCulture);
            }
        }
        
        internal static string Asteroid_Density_High {
            get {
                return ResourceManager.GetString("Asteroid_Density_High", resourceCulture);
            }
        }
        
        internal static string Arena_Random {
            get {
                return ResourceManager.GetString("Arena_Random", resourceCulture);
            }
        }
        
        internal static string Windowed {
            get {
                return ResourceManager.GetString("Windowed", resourceCulture);
            }
        }
        
        internal static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        internal static string Display_Mode {
            get {
                return ResourceManager.GetString("Display_Mode", resourceCulture);
            }
        }
        
        internal static string Choose_Your_Ship {
            get {
                return ResourceManager.GetString("Choose_Your_Ship", resourceCulture);
            }
        }
        
        internal static string Battle_Arena_Is {
            get {
                return ResourceManager.GetString("Battle_Arena_Is", resourceCulture);
            }
        }
        
        internal static string Up_To_Change_Colour_Fire_To_Change_Ship {
            get {
                return ResourceManager.GetString("Up_To_Change_Colour_Fire_To_Change_Ship", resourceCulture);
            }
        }
        
        internal static string Controllers_Can_Shoot_In_All_Directions {
            get {
                return ResourceManager.GetString("Controllers_Can_Shoot_In_All_Directions", resourceCulture);
            }
        }
        
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        internal static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        internal static string Fire {
            get {
                return ResourceManager.GetString("Fire", resourceCulture);
            }
        }
        
        internal static string Mine {
            get {
                return ResourceManager.GetString("Mine", resourceCulture);
            }
        }
        
        internal static string Built_With_MonoGame {
            get {
                return ResourceManager.GetString("Built_With_MonoGame", resourceCulture);
            }
        }
        
        internal static string Font_By {
            get {
                return ResourceManager.GetString("Font_By", resourceCulture);
            }
        }
        
        internal static string Github_Repo {
            get {
                return ResourceManager.GetString("Github_Repo", resourceCulture);
            }
        }
        
        internal static string Game_Enhancements {
            get {
                return ResourceManager.GetString("Game_Enhancements", resourceCulture);
            }
        }
        
        internal static string No_Input_Device_Connected {
            get {
                return ResourceManager.GetString("No_Input_Device_Connected", resourceCulture);
            }
        }
    }
}
